apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  SONAR_JDBC_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
  SONAR_JDBC_USERNAME: postgres # TODO: Create specific user for sonar?
  SONAR_JDBC_PASSWORD: "your-secret-password" # TODO: Must use postgresql's defined secret
  SONARQUBE_WEB_CONTEXT: /sonar
