apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      securityContext:
        fsGroup: 1000
      # Fixes issues with permissions on hostPath bindings
      #      initContainers:
      #        - name: fix-permissions
      #          image: busybox
      #          command: ["sh", "-c", "chmod -R 777 /opt/sonarqube && chown -R 1000:1000 /opt/sonarqube"]
      #          securityContext:
      #            privileged: true
      #          volumeMounts:
      #            - name: sonarqube-data
      #              mountPath: /opt/sonarqube
      containers:
        - name: sonar
          envFrom:
            - configMapRef:
                name: sonar-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/system/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

## Removing volues as we're ok with an ephemeral installation
#          volumeMounts:
#            - name: sonarqube-data
#              mountPath: /opt/sonarqube/data
#            - name: sonarqube-logs
#              mountPath: /opt/sonarqube/logs
#            - name: sonarqube-extensions
#              mountPath: /opt/sonarqube/extensions
#
#      volumes:
#        - name: sonarqube-data
#          persistentVolumeClaim:
#            claimName: sonarqube-pvc
#        - name: sonarqube-logs
#          emptyDir: {} # or separate PVC if you want persistence
#        - name: sonarqube-extensions
#          emptyDir: {} # or separate PVC if you want persistence
