apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

bases:
  - ../../base

# TODO: Define what kind of patching is needed
# patchesStrategicMerge:
#  - replica-patch.yaml
#  - configmap-patch.yaml
#  - ingress-patch.yaml

commonLabels:
  environment: dev
