apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

bases:
  - ../../base

# TODO: Define what kind of patching is needed
patchesStrategicMerge:
 - nginx-test/replica-patch.yaml
 - nginx-test/ingress-patch.yaml

commonLabels:
  environment: dev
