apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "10240Mi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /pgadmin/misc/ping
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /pgadmin/misc/ping
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
