name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    environment:
      name: ${{ matrix.environment }}
      url: ${{ matrix.environment == 'dev' && 'http://dev.local' || matrix.environment == 'staging' && 'http://staging.local' || 'http://prod.local' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          addons: ingress
          driver: docker  
        
      - name: Verify minikube & kubectl access
        run: |
          echo "Verify minikube & kubectl access..."
          minikube status || true
          kubectl version --client
          kubectl config current-context

      - name: Run ArgoCD prerequisites script
        run: |
          echo "Run ArgoCD..."
          chmod +x k8n/prerequisites/argocd/install.sh
          bash k8n/prerequisites/argocd/install.sh          

      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploy to ${{ matrix.environment }}..."
          kubectl apply -k k8n/overlays/${{ matrix.environment }}

      - name: Verify deployment
        run: |
          echo "Verificando el despliegue en ${{ matrix.environment }}..."
          kubectl get pods -n ${{ matrix.environment }}
          kubectl get svc -n ${{ matrix.environment }}

      - name: Deployment complete
        run: echo "¡Despliegue en ${{ matrix.environment }} finalizado!" 